grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30000
  adminPassword: admin
  ingress:
    enabled: false

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 9090
  ingress:
    enabled: false

alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 9091
  ingress:
    enabled: false
