grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30000
  adminPassword: admin
  ingress:
    enabled: false

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 30001
  ingress:
    enabled: false

alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 30002
  ingress:
    enabled: false
